version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  express:
    build: .
    restart: always
    ports:
      - "80:80"
    environment:
      DB_HOST: "mongodb://root:root@mongo:27017"
      NODE_ENV: "production"
      PORT: "80"
      SECRET: "she0eeLurujiez5KKew8YiS6"