version: '3.9'
services:
  mongo:
    image: mongo
    container_name: final-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  backend:
    build: .
    container_name: final-backend
    restart: always
    expose:
      - "8080"
    environment:
      DB_HOST: "mongodb://root:root@mongo:27017"
      NODE_ENV: "production"
      PORT: "8080"
      TOKEN_SECRET: "she0eeLurujiez5KKew8YiS6"
      UPDATE_CACHE_CRON: "0 12 * * *"

  nginx:
    container_name: final-nginx
    build:
      context: final-front/
      dockerfile: Dockerfile
    environment:
      BACKEND_HOST: "http://backend:8080"
    volumes:
      - ./final-front/dist:/usr/share/nginx/html
      - ./final-front/src/templates:/usr/share/nginx/html/templates
      - ./final-front/images/:/usr/share/nginx/html/images
    ports:
      - "3030:80"